modules:
- config:
    global:
      output_dir: <args:2>
  module: main.Initializer
- config:
    path: <args:1>
  module: loader.ObjectLoader
- config:
    lights:
    - energy: 1000
      location:
      - 5
      - -5
      - 5
      type: POINT
  module: lighting.LightLoader
- config:
    file_format: location rotation/value
    intrinsics:
      fov: 1
    path: <args:0>
  module: camera.CameraLoader
- config:
    distance_output_key: distance
    normals_output_key: normals
    output_key: colors
    render_distance: true
    render_normals: true
    samples: 350
  module: renderer.RgbRenderer
- config:
    postprocessing_modules:
      distance:
      - module: postprocessing.TrimRedundantChannels
  module: writer.Hdf5Writer
setup:
  blender_install_path: /home/khaled/opt/blender-2.91.0-linux64
  pip:
  - h5py
version: 3
